# Generated by Django 3.2.19 on 2023-08-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('availableqty', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=30)),
                ('vendorid', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'registration model',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('tdate', models.DateTimeField(auto_now=True)),
                ('qty', models.DateTimeField(auto_now=True)),
                ('modeofpayment', models.CharField(max_length=100)),
                ('distributor', models.CharField(max_length=100)),
                ('deliverystatus', models.CharField(max_length=100)),
                ('paymentstatus', models.CharField(max_length=100)),
                ('vendorlocation', models.CharField(max_length=100)),
                ('customerlocation', models.CharField(max_length=100)),
                ('vendorid', models.CharField(max_length=100)),
                ('txamount', models.CharField(max_length=100)),
            ],
        ),
    ]
